EXECUTABLE=shell
CFLAGS= -Wall -g

shell.o: main.c
	gcc $(CFLAGS) -o $(EXECUTABLE) head_list.c head_list.h libraries-headers.h AuxiliarFunctions.c AuxiliarFunctions.h commands.c commands.h main.c list_blocks.c list_blocks.h
